services:
  # PostgreSQL database for development
  postgres:
    image: postgres:16
    container_name: remarket-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remarket
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Next.js frontend application in development mode
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: remarket-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/remarket
      # Add any other environment variables your app needs for development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: /app/docker-entrypoint.sh
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-dev-data:

networks:
  default:
    name: remarket-dev-network
    driver: bridge 