services:

  postgres:
    image: postgres:16
    container_name: remarket-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remarket
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webapp:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: remarket-webapp-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/remarket
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "pnpm db:migrate && pnpm dev"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-dev-data:

networks:
  default:
    name: remarket-dev-network
    driver: bridge
